### ISSUE TITLE
press/release binding for uosc overwritten?

### ISSUE THREAD

**Issue by xfzv** [Natural-Harmonia-Gropius/InputEvent#14]
1. In `input.conf`, use either:

```
TAB        script-binding uosc/toggle-ui        #@press
TAB        script-binding uosc/toggle-ui        #@release

# or

TAB        script-message-to uosc toggle-elements timeline        #@press
TAB        script-message-to uosc toggle-elements timeline        #@release
```

2. Press <TAB> and release: works as expected
3. Press <TAB> once (can happen by mistake)
4. Try to press/release again: no longer works, the command bound to `TAB` is now toggled when single pressing `TAB`

Is this expected?

**Comment by Natural-Harmonia-Gropius** [comment]
fixed by https://github.com/Natural-Harmonia-Gropius/InputEvent/commit/5099091abf914ba40017a00aaad8337fd6b96f14 and https://github.com/Natural-Harmonia-Gropius/InputEvent/commit/d94a90f2dbad97643834a329ac149b3608f29163.
