### ISSUE TITLE
允许通过脚本配置文件设置绑定

### ISSUE THREAD

**Issue by zhongfly** [Natural-Harmonia-Gropius/InputEvent#22]
部分osc或gui前端同样使用input.conf中的#注释来构建右键菜单，此时有可能使得InputEvent或osc/gui一方不能按预期工作（虽然目前没有），或者是gui支持可视化input.conf时脚本的重复绑定可能会使之产生问题。
可以考虑支持通过配置文件`script-opts\InputEvent.conf`来设置键位绑定设置是从input.conf中读取，还是从自定义的其他文件中读取

这个“自定义的其他文件”，它的语法可以和input.conf一致，使代码可以复用；当从自定义文件读取时，可能出现click重复绑定的问题，~~希望可以允许设定是优先input.conf中的（脚本仍会读取input.conf但忽略其中注释部分的InputEvent设置，仅用于设定click），还是优先自定义配置的（即覆盖input.conf中的绑定），也可以考虑直接忽略自定义配置里的click绑定。可以结合 https://github.com/Natural-Harmonia-Gropius/InputEvent/issues/20#issuecomment-1316845458 的设想添加优先级~~ 从配置分离来考虑，应该是尊重input.conf中的绑定，但是不从那里读取脚本扩展的事件绑定，视之为最低优先级的click绑定（当没有实现 #20 时，则应该是用input.conf覆盖掉外部配置的click绑定）

**Comment by zhongfly** [comment]
我觉得也是彻底解决https://github.com/Natural-Harmonia-Gropius/InputEvent/issues/11 之类问题的方法
虽然会使得键位绑定的设置分散

**Comment by zhongfly** [comment]
https://github.com/zhongfly/InputEvent/commit/86cfe86f8b82376b438ff932c3b08ae259ed8b0e

先改了一个简单的，获取mpv当前的绑定，覆盖外部配置文件的click。
可以自定义配置文件地址，外部配置的语法和现在的input.conf完全一致

**Comment by hooke007** [comment]
我不理解为什么要把函数局部化。。。

**Comment by zhongfly** [comment]
> 我不理解为什么要把函数局部化。。。

1，局部变量访问更快
2，没有坏处

**Comment by hooke007** [comment]
访问更快是否有验证依据。如果更快mpv内最复杂的osc脚本没理由不使用

**Comment by zhongfly** [comment]
> 访问更快是否有验证依据。如果更快mpv内最复杂的osc脚本没理由不使用

这是lua语言自身的特性，https://stackoverflow.com/questions/9132288/why-are-local-variables-accessed-faster-than-global-variables-in-lua

**Comment by hooke007** [comment]
..这并没有解释我的疑问
假设成立，为什么还有遗漏的函数并没有统一为局部

**Comment by zhongfly** [comment]
> ..这并没有解释我的疑问 假设成立，为什么还有遗漏的函数并没有统一为局部

xx:xx这种函数担心改了会出问题，也懒得查文档，所以懒得改

**Comment by hooke007** [comment]
按照网上的做了测试，用了局部的话最好还是全部统一局部
```lua
-- 无报错
local function test()
    test1()
    test2()
end
function test1()
    print("test1")
end
function test2()
    print("test2")
end
test()
```

```lua
-- 报错
local function test()
    test1()
    test2()
end
function test1()
    print("test1")
end
local function test2()
    print("test2")
end
test()
```

**Comment by zhongfly** [comment]
> 按照网上的做了测试，用了局部的话最好还是全部统一局部

https://www.lua.org/pil/6.2.html
主要还是变量应该先定义后使用吧，这个脚本里都是先定义，后使用的，所以不会报错

以下不会报错
```lua
function test1()
    print("test1")
end
local function test2()
    print("test2")
end
local function test()
    test1()
    test2()
end
test()
```

**Comment by hooke007** [comment]
先声明肯定是不报错啦，这也算是发现一个特性了

**Comment by zhongfly** [comment]
> > ..这并没有解释我的疑问 假设成立，为什么还有遗漏的函数并没有统一为局部
> 
> xx:xx这种函数担心改了会出问题，也懒得查文档，所以懒得改

补充说明，object:method这种形式的函数，实际上是给object添加函数方法，如果定义为local，则只能在对象内部进行调用，即私有方法，不可以在外部通过object:method()来运行。

https://www.lua.org/pil/16.4.html 说的不太清楚
