### ISSUE TITLE
It broke scroll-list.lua functionality

### ISSUE THREAD

**Issue by BhaturaGuy** [Natural-Harmonia-Gropius/InputEvent#34]
https://github.com/CogentRedTester/mpv-scroll-list
I use [chapter-list.lua](https://github.com/CogentRedTester/mpv-scroll-list/blob/master/examples/chapter-list.lua)
Scroll wheel and UP, DOWN were used to scroll among chapters.
UP, Down and Scroll Wheel are now just changing volume.

**Comment by Natural-Harmonia-Gropius** [comment]
can you share your input.conf?

**Comment by BhaturaGuy** [comment]
input.conf isn't required since just dropping `inputevent.lua` to my scripts folder makes chapterlist.lua to ignore

```
add_keys(o.key_scroll_down, 'scroll_down', function() list:scroll_down() end, { repeatable = true })
add_keys(o.key_scroll_up, 'scroll_up', function() list:scroll_up() end, { repeatable = true })
add_keys(o.key_move_pageup, 'move_pageup', function() list:move_pageup() end, {})
add_keys(o.key_move_pagedown, 'move_pagedown', function() list:move_pagedown() end, {})
add_keys(o.key_move_begin, 'move_begin', function() list:move_begin() end, {})
add_keys(o.key_move_end, 'move_end', function() list:move_end() end, {})
add_keys(o.key_open_chapter, 'open_chapter', open_chapter, {})
add_keys(o.key_close_browser, 'close_browser', function() list:close() end, {})
```
But it doesn't hamper `mp.register_script_message("toggle-chapter-browser", function() list:toggle() end)` since it is in my input.conf `TAB script-message-to chapter_list toggle-chapter-browser`.
Maybe it can be fixed by adding them in input.conf? But then again I use UP, DOWN and scroll wheel for volume. And their function is only different when `toggle-chapter-browser` is in focus.

**Comment by Natural-Harmonia-Gropius** [comment]
Weird, I just add `script-message-to chapter_list toggle-chapter-browser` too.
Can you show your `shift+i` `4`? See what's taking up `wheel_up`.

![image](https://user-images.githubusercontent.com/50797982/213672495-ff6f137e-9068-4652-8ee4-cbc1e47ecafc.png)
![image](https://user-images.githubusercontent.com/50797982/213672836-d1381bb6-df82-4b4c-bf46-1b650839b4fb.png)

**Comment by BhaturaGuy** [comment]
![image](https://user-images.githubusercontent.com/93109835/213675687-312b2e2f-9a3a-4aec-948f-8ed7b24a7aa3.png)
Also I just noticed, I can click on timeline with left click now.
I had buttons in uosc as some binds even they stopped working, though I can use them using keybinds
Almost everything broke.

**Comment by Natural-Harmonia-Gropius** [comment]
You can scroll down this page to find the wheel_up and wheel_down.

Does everything work well if you delete inputevent.lua?

**Comment by BhaturaGuy** [comment]
> Does everything work well if you delete inputevent.lua?

Yes.

**Comment by Natural-Harmonia-Gropius** [comment]
Any error or warning in console? " ` " <- default tothis key

**Comment by Natural-Harmonia-Gropius** [comment]
I have no idea what's happening here.

Can you upload your mpv.conf?

If you delete this part (at end of inputevent.lua), does everything works?
![image](https://user-images.githubusercontent.com/50797982/213683560-e8a90b13-21c5-4f14-b050-06b3eea10e63.png)

**Comment by BhaturaGuy** [comment]
Upon closer inspection, this seems to be an issue of another script/or maybe mpv.
Sorry for wasting your time.
