### ISSUE TITLE
First two examples don't work for me

### ISSUE THREAD

**Issue by omnosti** [Natural-Harmonia-Gropius/InputEvent#58]
Using the first two examples, a single left click fullscreens the video and spacebar does nothing at all. I'm on the latest windows builds from zhongfly, and I tried deleting every other script I have but the result is the same.

**Comment by natural-harmonia-gropius** [comment]
Are you using the script from release or master? If it is the release version, please switch to the master script.

**Comment by omnosti** [comment]
I was using the release version, everything works now with the master branch version. Thank you!
