### ISSUE TITLE
Seek cannot work after changing to RIGHT

### ISSUE THREAD

**Issue by Thintime1998** [Natural-Harmonia-Gropius/InputEvent#59]
Seek cannot work after changing to RIGHT

**Comment by natural-harmonia-gropius** [comment]
Can you share your input.conf about RIGHT and what's before?

**Comment by Thintime1998** [comment]
RIGHT seek  5
RIGHT     no-osd set speed 3; set pause no    #event: press
RIGHT     ignore                              #event: release

**Comment by Thintime1998** [comment]
MBTN_LEFT     ignore
MBTN_LEFT_DBL cycle fullscreen
MBTN_RIGHT    cycle pause
MBTN_BACK     seek -5
MBTN_FORWARD  seek 5

WHEEL_UP      add volume 5
WHEEL_DOWN    add volume -5
WHEEL_LEFT    seek 5
WHEEL_RIGHT   seek -5

ESC quit
SPACE cycle pause
ENTER cycle fullscreen
f cycle fullscreen
F cycle fullscreen
\ show-progress
` script-binding console/enable
tab script-binding stats/display-stats
? script-binding stats/display-stats-toggle

t cycle ontop
r stay

UP    add volume 5
DOWN  add volume -5
Shift+UP    add volume  10
Shift+DOWN  add volume -10

LEFT  seek -5
RIGHT seek  5
RIGHT     no-osd set speed 3; set pause no    #event: press
RIGHT     ignore                              #event: release

Ctrl+LEFT  seek -10 exact
Ctrl+RIGHT seek 10 exact
Shift+LEFT  seek -30 exact
Shift+RIGHT seek 30 exact

Ctrl+Shift+UP add audio-delay -0.1
Ctrl+Shift+DOWN add audio-delay +0.1

,   add sub-delay -0.1
.  add sub-delay 0.1
Ctrl+Shift+LEFT add sub-delay  -1
Ctrl+Shift+RIGHT add sub-delay  1

z set speed 1.0
c add speed 1.0
x add speed -1.0
Z set speed 1.0
C add speed 1.0
X add speed -1.0
Shift+PGUP multiply speed 2.0
Shift+PGDWN multiply speed 0.5

PGUP playlist-prev
PGDWN playlist-next

[ frame-back-step
] frame-step
{ add chapter -1
} add chapter 1
# F1 add current-window-scale -0.1 	
# F2 add current-window-scale  0.1

**Comment by natural-harmonia-gropius** [comment]
```
RIGHT seek 5 #event: click
RIGHT no-osd set speed 3; set pause no #event: press
RIGHT ignore #event: release
```

**Comment by Thintime1998** [comment]
Okay, thank you very much
