### ISSUE TITLE
will add compatibility with mpv-menu-plugin

### ISSUE THREAD

**Issue by Shinkir0** [Natural-Harmonia-Gropius/InputEvent#60]
I use https://github.com/tsl0922/mpv-menu-plugin and there template file input.conf is different from the standard one, is it possible to add compatibility with it?

**Comment by natural-harmonia-gropius** [comment]
Doesn't this works?

`SPACE       cycle pause           #event: click     #menu: Play  #@state=(idle_active and 'disabled' or (pause or 'hidden'))`

**Comment by Shinkir0** [comment]
you are right it works this way, I made a mistake in the command
