### ISSUE TITLE
Shouldn't have repeat before press.

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [Natural-Harmonia-Gropius/InputEvent#9]
https://github.com/Natural-Harmonia-Gropius/InputEvent#press-to-speedup-release-to-restore

I've been thinking about it for a while, and it looks like the step acceleration in evafast can be done like this.
We can do more in command of repeat, like max_speed. If https://github.com/Natural-Harmonia-Gropius/InputEvent/issues/4 could be done.
But as the title, repeat before press can cause a bad experience.

```
SPACE           cycle pause                         #@click
SPACE           no-osd set speed 1; set pause no    #@press
SPACE           ignore                              #@release
SPACE           no-osd add speed 0.1                #@repeat
```

**Comment by po5** [comment]
I have a question about your evafast example, what is the benefit over the built-in logic of `RIGHT script-binding evafast`?  
It's registered as a repeatable complex keybind and detects all states.  
Have I missed something that makes it undesirable in some way? Thanks.

**Comment by Natural-Harmonia-Gropius** [comment]
> what is the benefit over the built-in logic of

If the user wants to use both scripts to get customized behavior of the `RIGHT` of repeat, click and *_click.
Maybe someone did, although I wouldn't do it

Another point is that `add_forced_key_binding` will override `mp.add_key_binding("RIGHT", "evafast", evafast, {repeatable = true, complex = true})`.
